# Generated by Django 2.2.7 on 2020-02-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagged_img', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedetail',
            name='visited',
            field=models.BooleanField(default=False),
        ),
    ]
