# Generated by Django 2.2.7 on 2020-04-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20200413_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupoftitle',
            name='checkin_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='groupoftitle',
            name='checkout_time',
            field=models.DateTimeField(),
        ),
    ]
