# Generated by Django 2.2.12 on 2020-06-14 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_auto_20200614_0208'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0004_auto_20200413_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupoftitle',
            name='name',
        ),
        migrations.RemoveField(
            model_name='groupoftitle',
            name='position',
        ),
        migrations.RemoveField(
            model_name='timekeeping',
            name='age',
        ),
        migrations.RemoveField(
            model_name='timekeeping',
            name='emo',
        ),
        migrations.RemoveField(
            model_name='timekeeping',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='timekeeping',
            name='last_checkin',
        ),
        migrations.RemoveField(
            model_name='timekeeping',
            name='last_checkout',
        ),
        migrations.RemoveField(
            model_name='timekeeping',
            name='name',
        ),
        migrations.RemoveField(
            model_name='timekeeping',
            name='prob',
        ),
        migrations.AddField(
            model_name='groupoftitle',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timekeeping',
            name='image_detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.ImageDetail'),
        ),
        migrations.AddField(
            model_name='timekeeping',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='camera',
            name='status',
            field=models.CharField(choices=[('Active', 'ACTIVE'), ('Paused', 'PAUSED'), ('Disabled', 'DISABLED')], default='Paused', max_length=10),
        ),
        migrations.CreateModel(
            name='UserExtraData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='')),
                ('age', models.IntegerField()),
                ('about_me', models.TextField()),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.Organization')),
            ],
        ),
    ]
