"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')n-orbf@qz0320)t9(o+vi42olczoqla15q#u&&24*6p$)7b58'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '0.0.0.0',
    'ai.nccsoft.vn'
]

SECURE_HSTS_SECONDS = 1
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False
SECURE_SSL_REDIRECT = False
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = True
X_FRAME_OPTIONS = 'DENY'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Django sites app  required
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    # apps
    'tools',
    'management',
    'crispy_forms',
]

# DJANGO CRISPY FORMS PACKAGE SETTING
CRISPY_TEMPLATE_PACK = 'bootstrap4'
# END OF DJANGO CRISPY FORMS PACKAGE SETTING

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static")

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    # '/var/www/static/',
]

MEDIA_URL = '/media/'
MEDIAFILES_DIR = [
    os.path.join(BASE_DIR, "media"),
    # '/var/www/media/',
]

# temporary image files location:
TEMP_IMG = 'cls/'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'management.report'

# TAG LIST
TAG_LIST = tags = [
    "Attila_Biro",
    "Ban_Le_Anh",
    "Bui_Anh_Tuan",
    "Bui_Minh_Anh",
    "Bui_Minh_Thai",
    "Bui_Quoc_Khanh",
    "Bui_Tuan_Dat",
    "Bui_Van_Lam",
    "Cao_Thi _Hoan",
    "Dang_An_Thien",
    "Dang_Danh_Phuong",
    "Dang_Quoc_Viet",
    "Dang_Van_Tuyen",
    "Dao_Thi_Duong",
    "Dinh_Thanh_Thuong",
    "Dinh_Tuan",
    "Doan_Manh_Hoang",
    "Doan_Thanh",
    "Do_Duc_Trung",
    "Do_Hoang_Hieu",
    "Do_Phu_Huong",
    "Do_Thi_Thuy",
    "Do_Trong_Trung",
    "Do_Tuan_Anh",
    "Dung_Comter",
    "Dung_Viettel",
    "Duong_Chi_Trung",
    "Duong_Thi_Quynh",
    "Duong_Van_Phuc",
    "Duong_Viet_Hung",
    "Em_Le_Anh",
    "Hoang_Dinh_Trung",
    "Hoang_Game_Dev",
    "Hoang_Thi_Mo",
    "Hoang_Tuan_Vu",
    "Nguyen_Anh_Tuan",
    "Nguyen_Cong_Toai",
    "Nguyen_Dai_Duong",
    "Nguyen_Dinh_Minh",
    "Nguyen_Duc_Hoang",
    "Nguyen_Hoang_Long (TTS)",
    "Nguyen_Hong_Nhat",
    "Nguyen_Huong_Cuc",
    "Nguyen_Huu_Hao",
    "Nguyen_Huu_Tien",
    "Nguyen_Le_Linh",
    "Nguyen_Manh_Quan",
    "Nguyen_Nam_Hieu",
    "Nguyen_Ngan_Ha",
    "Nguyen_Nhu_Vinh",
    "Nguyen_Phuong_Anh",
    "Nguyen_Phuong_Nam",
    "Nguyen_Son_Tung",
    "Nguyen_Thai_Vinh",
    "Nguyen_Thanh_Tung",
    "Nguyen_Thi_Hoa",
    "Nguyen_Thi_Hong_Anh",
    "Nguyen_Thi_Ly",
    "Nguyen_Thi_Ly_Hoang",
    "Nguyen_Thi_Ngoc",
    "Nguyen_Thi_Phuong_Anh",
    "Nguyen_Thi_Thao",
    "Nguyen_Thi_Thu_Ha",
    "Pham_Toan_Thang",
    "Pham_Trung_Hieu",
    "Pham_Tuan_Minh",
    "Pham_Viet_Thang",
    "Phan_Hoang_Lam",
    "Phan_Thi_Thanh_Hai",
    "Sim",
    "Song_Gianh",
    "Ta_Van_Quang",
    "Thuy_Anh",
    "Tran_Duc_Hung",
    "Tran_Huy_Tung",
    "Tran_Le_Anh",
    "Tran_Ngoc_Van",
    "Tran_Thuy_An",
    "Tran_Van_Binh",
    "Trinh_Duc_Dai",
    "Trinh_Quoc_Vuong",
    "Tuan_Linh",
    "Unknown",
    "Vo_Nguyen_Le_Linh",
    "Vo_Nguyen_Tran_Nhan",
    "Vo_Pham_Manh_Tien",
    "Vuong_Thuy_Anh",
    "Vu_Hong_Ha_Anh",
    "Vu_Lenh_Tho",
    "Vu_Nhu_Hai",
    "Vu_Thi_Van",
    "Vu_Van_Huy",
    "Hong_Tester",
    "HR_1",
    "Le_Dang_Quang",
    "Le_Duc_Nhat_Ninh",
    "Le_Huu_Hoang_Anh",
    "Le_Thanh_Trung",
    "Le_Thi_Dung",
    "Le_Thi_Thuy_Quynh",
    "Le_Thi_Tram_Anh",
    "Le_Van_An",
    "Le_Xuan_Hai",
    "Le_Xuan_Truong",
    "Lo_Van_Kien",
    "Luc_Van_Minh",
    "Luu_Ha_Phuong",
    "Mai_The_Hung",
    "Mai_The_Lanh",
    "Ma_Van_Tu",
    "Moha",
    "Nghiem_Thu_Thuy",
    "Ngo_Thu_Hien",
    "Ngo_Tri _Dat",
    "Hoa_Tester_BTM",
    "Nguyen_Anh_Hoang",
    "Nguyen_Thi_Yen",
    "Pham_Thi_Theu",
    "Nguyen_Thuy_Trang",
    "Nguyen_Tran_Nam_Long",
    "Nguyen_Tran_Ngoc_Nhi",
    "Nguyen_Tran_Nhan",
    "Nguyen_Truc_Quynh_Huong",
    "Nguyen_Tuan_Tung",
    "Nguyen_Van_Long",
    "Nguyen_Van_Tuan",
    "Nguyen_Van_Tung",
    "Nguyen_Xuan_Hoang",
    "Nhung_Vo_Hao",
    "Noname_Android_1",
    "Noname_giong_Xuan_Hoang",
    "Noname_TTS_1",
    "Noname_TTS_2",
    "Noname_TTS_4",
    "Noname_TTS_5",
    "Noname_TTS_6",
    "Pham_Manh_Tien",
    "Pham_Minh_Tuan",
    "Pham_Minh_Tuan (TTS)",
    "Pham_Ngoc_Canh",
    "Pham_Phuc_Thuan",
    "Pham_Quang_Vinh",
    "Pham_Thanh_Tung",
]
