# Generated by Django 2.2.12 on 2020-06-14 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0003_auto_20200327_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedetail',
            name='visited',
        ),
        migrations.AddField(
            model_name='imagedetail',
            name='image_name',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='imagedetail',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='imagedetail',
            name='top1_prob',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='imagedetail',
            name='top2_prob',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='imagedetail',
            name='top3_prob',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='imagedetail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagedetail',
            name='user_prob',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=5),
        ),
    ]
