# Generated by Django 2.2.7 on 2020-04-13 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_cameralist_groupoftitle_organization'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CameraList',
            new_name='Camera',
        ),
    ]
